[package]
name = "candle5"
version = "0.1.0"
edition = "2024"

[dependencies]
helper = { path = "../helper" }
anyhow = { workspace = true }
serde = { workspace = true }
serde-jsonlines.workspace = true
chrono = { workspace = true }
itertools = { workspace = true }
rayon = { workspace = true }
